# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
parameters:
  testname:
    type: string
    default: ""
jobs:
  run_tests:
    docker:
      # specify the version you desire here
      - image: circleci/node:12-browsers
    working_directory: ~/cboard-webdriverio
    steps:
    - checkout
    - restore_cache:
        keys:
          # when lock file changes, use increasingly general patterns to restore cache
          - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-packages-v1-{{ .Branch }}-
          - yarn-packages-v1-
    # Install and save node_modules to cache
    - run:
        name: Install dependencies
        command: |
          yarn install  --ignore-engines --ignore-platform --cache-folder ~/.cache/yarn
    - save_cache:
        paths:
          - ~/.cache/yarn
        key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
    # run tests!
    - run:
        name: Run wdio tests
        command: |
          TEST_FILES=$(circleci tests glob "**/test/*.spec.ts")
          echo "$TEST_FILES" | circleci tests run --command="xargs yarn test --spec << pipeline.parameters.testname >>" --verbose
    - store_test_results:
        path: test-results

workflows:
  version: 2
  qa_test:
    jobs:
      - run_tests:
          context: qa-users
          filters:
            branches:
              only: master